# application.yml

general:
  kafka-topic: my-kafka-topic

# Kafka server properties
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group ,midas-consumer-group

      auto-offset-reset: earliest
    producer:
      acks: all
    listener:
      topic: # The Kafka topic will be specified here
